# Differences between Python and Matlab

Below, I have copied our Matlab session with details. 

Here is a summary of the most important differences between Python and Matlab:

| Concept              |      Python                     |     Matlab                    |
|----------------------|---------------------------------|-------------------------------|
| Vector               | `xs = [1,2,3]` <br> (or `np.array([1,2,3])`)|   `v = [1 2 3]`   |
| Matrix               |  list of lists or numpy array of shape `(m,n)` |  same as vector, use `;` to separate rows      |
| default type of number   | `float` or `int` based on syntax e.g. `1.0` vs `1` |   default is float (double precision) |
| accessing element in vector/list |  `xs[i]` | v(i) |
| indexing            |  starts from `0`   | starts from `1`. e.g. `v(1) = 1` for `v = [1 2 3]` |
|last element |  `xs[-1]` |  `v(end)` |
| slicing             |  `xs = [1,2,3,4]`, `xs[1:3]` is `[2,3]`  |  `v = [1 2 3 4]`, `v(1:3)` is `[1 2 3]` 
| range               |  `list(range(10))`  | `0:9`  |
| steppy range        |  `list(range(0,10,2))` |  `0:2:8` 
| strings             |  `"asdf"` or `'asdf'`        |   only `'asdf'` |
| Price               |   Free and **open source**       | Costs money, not open source (this also has *some* advantages, e.g. certain specialized libraries are better) |

Other important points:

Variables are always copied by value (not by reference, so **none of the mutable/immutable distinction**). E.g.:

    v = [1 2 3]
    w = v
    w(1) = 999
    
Will change the first element of `w` but not of `v`. (Recall that this differs from Python where `w=v` would make `w` point to the same list as `v` and any change in `w`'s elements would change the same element in `v`)



Here are the concepts discussed in the transcript of the Matlab session that follows:

* vectors, matrices etc.
* series with specified increment
* accessing index in vector or matrix, slicing
* size
* transpose
* matrix multiplication is built-in `*`
* element-wise multiplication `.*`
* for, while, if-else formatting
* `eps`, `realmax`, `realmin`, `Inf`, `pi`
* you can make scripts with `.m` file format
* basic plotting (surprise: it's exactly the same)

```
# for loops
x = ones(1,10);
for n = 2:6
    x(n) = 2 * x(n - 1);
end


# if-else:
if r == c
    A(r,c) = 2;
elseif abs(r-c) == 1
    A(r,c) = -1;
else
    A(r,c) = 0;
end


# Function syntax:
# y and z are returned

function [y z]= average(x)
if ~isvector(x)
    error('Input must be a vector')
end
y = sum(x)/length(x);
z = 1
end
```

### Our Matlab Session:

```
Trial>> v = [1 2 3]

v =

     1     2     3

Trial>> v = [1 2 3]'

v =

     1
     2
     3

Trial>> M = [1 2 3; 4 5 6; 7 8 9]

M =

     1     2     3
     4     5     6
     7     8     9

Trial>> M'

ans =

     1     4     7
     2     5     8
     3     6     9

Trial>> M''

ans =

     1     2     3
     4     5     6
     7     8     9

Trial>> M'';
Trial>> M = M'';
Trial>> M = M''

M =

     1     2     3
     4     5     6
     7     8     9

Trial>> M * M

ans =

    30    36    42
    66    81    96
   102   126   150

Trial>> eye(3)

ans =

     1     0     0
     0     1     0
     0     0     1

Trial>> M

M =

     1     2     3
     4     5     6
     7     8     9

Trial>> M .* M

ans =

     1     4     9
    16    25    36
    49    64    81

Trial>> M(1,1)

ans =

     1

Trial>> M(2,2)

ans =

     5

Trial>> M

M =

     1     2     3
     4     5     6
     7     8     9

Trial>> M(1:2,1:2)

ans =

     1     2
     4     5

Trial>> M(2:3,2:3)

ans =

     5     6
     8     9

Trial>> 1:10

ans =

     1     2     3     4     5     6     7     8     9    10

Trial>> 1:2:10

ans =

     1     3     5     7     9

Trial>> 1:2:10

ans =

     1     3     5     7     9

Trial>> 1:2:11

ans =

     1     3     5     7     9    11

Trial>> v = 1:15

v =

     1     2     3     4     5     6     7     8     9    10    11    12    13    14    15

Trial>> v(1:10:2)

ans =

     1

Trial>> v(1:2:10)

ans =

     1     3     5     7     9

Trial>> v

v =

     1     2     3     4     5     6     7     8     9    10    11    12    13    14    15

Trial>> v(-1)
Subscript indices must either be real positive integers or logicals.

Trial>> v(end)

ans =

    15

Trial>> M

M =

     1     2     3
     4     5     6
     7     8     9

Trial>> size(M)

ans =

     3     3

Trial>> eps

ans =

   2.2204e-16

Trial>> Inf

ans =

   Inf

Trial>> realmax

ans =

  1.7977e+308

Trial>> realmin

ans =

  2.2251e-308

Trial>> figure
Trial>> v = 1:100

v =

  Columns 1 through 16

     1     2     3     4     5     6     7     8     9    10    11    12    13    14    15    16

  ...

Trial>> v = 0:0.01:1

v =

  Columns 1 through 9

         0    0.0100    0.0200    0.0300    0.0400    0.0500    0.0600    0.0700    0.0800

  ...
  
Trial>> plot(v .* v)
Trial>> title("awesome plot")
Trial>> rand(4)

ans =

    0.1067    0.8173    0.2599    0.1818
    0.9619    0.8687    0.8001    0.2638
    0.0046    0.0844    0.4314    0.1455
    0.7749    0.3998    0.9106    0.1361

Trial>> rand(2,50)

ans =

  Columns 1 through 9

    0.8693    0.5499    0.8530    0.3510    0.4018    0.2399    0.1839    0.4173    0.9027
    0.5797    0.1450    0.6221    0.5132    0.0760    0.1233    0.2400    0.0497    0.9448

   ...
   
Trial>> A = rand(2, 50)

A =

  Columns 1 through 9

    0.2967    0.4242    0.0855    0.8010    0.9289    0.4886    0.2373    0.9631    0.5211
    0.3188    0.5079    0.2625    0.0292    0.7303    0.5785    0.4588    0.5468    0.2316

  ...
  
Trial>> scatter(A(1), A(2))
Trial>> scatter(A(:,1), A(:,2))
Trial>> A = rand(100,1)

A =

    0.3724
    0.1981
    .
    .
    .
    
Trial>> B = rand(100,1)

B =

    0.2891
    0.6718
    .
    .
    .
    

Trial>> scatter(A, B)
```