In [1]:
i = 5
while i < 100:
    print(i)
    i *= 2
print(i)

5
10
20
40
80
160


In [2]:
def f(n):
    for i in range(10):
        if i > n:
            continue
        n = n // 2
    return n
print(f(32))

2


In [23]:
32//2
16//2
8//2
4//2

2

In [5]:
def g(n):
    if n == 0:
        return []
    return [n % 2] + g(n // 2)
print(g(10))

[0, 1, 0, 1]


In [6]:
list1=[1,1,1,1,2,2,2,2,3,3,3,3,4,4,4,4]
list2=[]
for i in range(1,5):
    list2=list2+[i]*4
print(list2)

[1, 1, 1, 1, 2, 2, 2, 2, 3, 3, 3, 3, 4, 4, 4, 4]


In [7]:
list1=[1,-1,2,-2,3,-3,4,-4,5,-5]
list2=[]
for i in range(1,6):
    list2.append(i)
    list2.append(-i)
print(list2)

[1, -1, 2, -2, 3, -3, 4, -4, 5, -5]


In [8]:
list1=[12,10,8,6,4,2,0,0,0,0]
list2=list(range(12,-1,-2))+[0]*3
print(list2)

[12, 10, 8, 6, 4, 2, 0, 0, 0, 0]


In [11]:
from functools import reduce
reduce(lambda x, y: x*y, range(1,7))

720

In [10]:
i=1
for j in range(2,6):
    i=i*j
print(i)

120


In [14]:
reduce(lambda a,d: 10*a+d, [1,2,3,4])

1234

In [15]:
def spread(xs):
    if len(xs)==0:
        return None
    current_max=xs[0]
    current_min=xs[0]
    for i in range(len(xs)):
        if current_max<xs[i]:
            current_max=xs[i]
        if current_min>xs[i]:
            current_min=xs[i]
    return current_max-current_min
spread([1,2,-1,5,10,12,0,0,4])

13

In [19]:
def gcd(x,y):
    while y!=0:
        r=x%y
        x=y
        y=r
    return x
print(gcd(120,35))

5


gcd(10,4)=gcd(4,2)=2


# Classes

Classes are sets of 'objects' where each object has similar attributes. Frequently, these objects will have 'methods' that allow us to perform operations on the objects.

## Example: Linked Lists

In [29]:
class Node(object):
    def __init__(self,data):
        if type(data) is (int or float or str):
            self.value=data
            self.next=None
            self.prev=None
        else:
            raise TypeError('data type not supported')
            

In [33]:
node=Node(52)
node.value
print(node.prev)

None


In [48]:
class LinkedList(object):
    def __init__(self):
        self.head=None
        self.tail=None
        self._size=0
    def __len__(self):
        return self._size
    def __str__(self):
        current=self.head
        str1='['
        while current is not None:
            str1=str1+str(current.value)+','
            current=current.next
        str1=str1[:-1]+']'
        return str1
    def append(self,data):
        new_node=Node(data)
        if self.head is None:
            self.head=new_node
            self.tail=new_node
        else:
            self.tail.next=new_node
            new_node.prev=self.tail
            self.tail=new_node
        self._size=self._size+1
    

In [49]:
list1=LinkedList()
list1.append(2)
print(list1.tail.value)
list1.append(3)
list1.append(4)
print(list1.head.value)
print(list1.tail.value)
print(list1.head.next.value)
print(len(list1))
print(str(list1))

2
2
4
3
3
[2,3,4]


In [50]:
import numpy as np

In [57]:
arr=np.array([[1,2,3],[4,5,6],[7,8,9]])

In [52]:
type(arr)

numpy.ndarray

In [58]:
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [59]:
arr.dtype

dtype('int32')

In [62]:
arr=arr.astype(float)

In [63]:
arr.dtype

dtype('float64')

In [67]:
arr[:,2]

array([ 3.,  6.,  9.])

In [68]:
print(np.zeros((3,4)))

[[ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]]


In [72]:
print(np.eye(4,3))

[[ 1.  0.  0.]
 [ 0.  1.  0.]
 [ 0.  0.  1.]
 [ 0.  0.  0.]]
