# Gaussian Elimination

Gaussian elimination is a method that will allow us to transform a matrix into an upper triangular matrix, in a useful way. To do this, we are allowed to perform several operations. We can multiply any row by a (nonzero) scalar, we can switch two rows, and we can replace a row with that row, added to a scalar times another row.

In summary, we allow the following:<br>
$R_i\rightarrow \lambda R_i$<br>
$R_i,R_j\rightarrow R_j,R_i$<br>
$R_i\rightarrow \lambda R_j+R_i$

Much of the value of the algorithm comes from applying it to an $n\times n+1$ matrix, to obtain an upper triangular $n\times n$ submatrix. To see why, consider an equation of the form $Ax=b$ where $x$ and $b$ are vectors, and $A$ is an $n\times n$ matrix. If we augment the matrix $A$ to a matrix $A'$ where the first $n$ columns of $A'$ are columns of $A$, and the last is the vector $b$, and then apply the algorithm, we obtain an $n\times n+1$ matrix $U'$ where the first $n$ columns of $U'$ form a matrix $U$, and the last column forms a vector $y$. $x$ is a solution of $Ux=y$.

Initially assume no row switches will be required to place an augmented matrix into reduce echelon form (the form where the first $n$ rows and columns of the resulting matrix form an upper triangular matrix). 

Let $A$ an $n\times(n+1)$ matrix

for $i=1\dots n$
>if $A(i,i)$ is nonzero
>> for $j=i+1\dots n$
>>> $R_j\rightarrow R_j+(-A(j,i)/A(i,i))R_i$<br>
>>> or $A[j,:]\rightarrow A[j,:]+(-A[j,i]/A[i,i])A[i,:]$

> else
>> return 'Method Failed'


Row switches are required if at some point, the $A(i,i)$ element is zero. In this case, we must switch the $ith$ row with some $jth$ row beneath it, that has the property that $A(j,i)$ is nonzero. If no such vector exists, then there will be no unique solution to the associated equation. In this case, return 'method failed'. 

Attempt to adjust the previous code to allow for the possibility of row swaps.

In [1]:
import numpy as np

In [2]:
A=np.array([[1,2,3,4],[2,3,5,6],[1,4,7,8]])
A[0,:]

array([1, 2, 3, 4])

In [4]:
A

array([[1, 2, 3, 4],
       [2, 3, 5, 6],
       [1, 4, 7, 8]])

In [5]:
def GaussElim(A):
    # Determine dimension of A
    n,columns=A.shape
    # make sure data type is float
    if type(A[0,0]) is not 'float':
        A=A.astype(float)
    print(type(A[0,0]))
    for i in range(0,n):
        if abs(A[i,i])<10**(-12):
            #look for a number under the (i i) element that is non zero
            for p in range(i+1,n):
                if abs(A[p,i])>10**(-12):
                    break
            if abs(A[p,i])>10**(-12):
            #switch rows of matrix
                A[[i,p]]=A[[p,i]]
            else:
                return 'method fails'
            
        
        
        
        
        for j in range(i+1,n):
            A[j,:]=A[j,:]-A[j,i]/A[i,i]*A[i,:]
    return A
    
            
        
    
    

In [6]:
print(GaussElim(A))

<class 'numpy.float64'>
[[ 1.  2.  3.  4.]
 [ 0. -1. -1. -2.]
 [ 0.  0.  2.  0.]]
